name: note_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  split_view: ^2.0.0
  window_manager: ^0.3.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
